"use client";
import React from "react";
import TextResource from "../entity/TextResource";
const fonts = [
  { fontFamily: "'Abril Fatface',cursive" },
  { fontFamily: "'Aclonica',sans-serif" },
  { fontFamily: "'Acme',sans-serif" },
  { fontFamily: "'Aladin',cursive" },
  { fontFamily: "'Alegreya SC',serif" },
  { fontFamily: "'Alegreya',serif" },
  { fontFamily: "'Alfa Slab One',cursive" },
  { fontFamily: "'Allan',cursive" },
  { fontFamily: "'Almendra',serif" },
  { fontFamily: "'Amaranth',sans-serif" },
  { fontFamily: "'Amita',cursive" },
  { fontFamily: "'Anton',sans-serif" },
  { fontFamily: "'Archivo Black',sans-serif" },
  { fontFamily: "'Arimo',sans-serif" },
  { fontFamily: "'Arizonia',cursive" },
  { fontFamily: "'Arvo',serif" },
  { fontFamily: "'Atomic Age',cursive" },
  { fontFamily: "'Audiowide',cursive" },
  { fontFamily: "'Bangers',cursive" },
  { fontFamily: "'Baumans',cursive" },
  { fontFamily: "'Bebas Neue',cursive" },
  { fontFamily: "'BenchNine',sans-serif" },
  { fontFamily: "'Berkshire Swash',cursive" },
  { fontFamily: "'BioRhyme',serif" },
  { fontFamily: "'Bitter',serif" },
  { fontFamily: "'Black And White Picture',sans-serif" },
  { fontFamily: "'Black Ops One',cursive" },
  { fontFamily: "'Bonbon',cursive" },
  { fontFamily: "'Boogaloo',cursive" },
  { fontFamily: "'Bungee Shade',cursive" },
  { fontFamily: "'Bungee',cursive" },
  { fontFamily: "'Butcherman',cursive" },
  { fontFamily: "'Butterfly Kids',cursive" },
  { fontFamily: "'Cabin Sketch',cursive" },
  { fontFamily: "'Cabin',sans-serif" },
  { fontFamily: "'Caesar Dressing',cursive" },
  { fontFamily: "'Cairo',sans-serif" },
  { fontFamily: "'Calligraffitti',cursive" },
  { fontFamily: "'Carter One',cursive" },
  { fontFamily: "'Caveat Brush',cursive" },
  { fontFamily: "'Caveat',cursive" },
  { fontFamily: "'Cedarville Cursive',cursive" },
  { fontFamily: "'Ceviche One',cursive" },
  { fontFamily: "'Changa',sans-serif" },
  { fontFamily: "'Chewy',cursive" },
  { fontFamily: "'Cinzel Decorative',cursive" },
  { fontFamily: "'Coda',cursive" },
  { fontFamily: "'Coiny',cursive" },
  { fontFamily: "'Comfortaa',cursive" },
  { fontFamily: "'Concert One',cursive" },
  { fontFamily: "'Cormorant Garamond',serif" },
  { fontFamily: "'Cormorant Infant',serif" },
  { fontFamily: "'Cormorant SC',serif" },
  { fontFamily: "'Cormorant Unicase',serif" },
  { fontFamily: "'Cormorant Upright',serif" },
  { fontFamily: "'Cormorant',serif" },
  { fontFamily: "'Courgette',cursive" },
  { fontFamily: "'Crimson Text',serif" },
  { fontFamily: "'DM Serif Text',serif" },
  { fontFamily: "'Dancing Script',cursive" },
  { fontFamily: "'David Libre',serif" },
  { fontFamily: "'Denk One',sans-serif" },
  { fontFamily: "'Dosis',sans-serif" },
  { fontFamily: "'East Sea Dokdo',cursive" },
  { fontFamily: "'Economica',sans-serif" },
  { fontFamily: "'El Messiri',sans-serif" },
  { fontFamily: "'Emilys Candy',cursive" },
  { fontFamily: "'Enriqueta',serif" },
  { fontFamily: "'Exo 2',sans-serif" },
  { fontFamily: "'Exo',sans-serif" },
  { fontFamily: "'Faster One',cursive" },
  { fontFamily: "'Finger Paint',cursive" },
  { fontFamily: "'Fira Sans',sans-serif" },
  { fontFamily: "'Fjalla One',sans-serif" },
  { fontFamily: "'Francois One',sans-serif" },
  { fontFamily: "'Frank Ruhl Libre',serif" },
  { fontFamily: "'Fredericka the Great',cursive" },
  { fontFamily: "'Fredoka One',cursive" },
  { fontFamily: "'Fugaz One',cursive" },
  { fontFamily: "'Galada',cursive" },
  { fontFamily: "'Gelasio',serif" },
  { fontFamily: "'Grand Hotel',cursive" },
  { fontFamily: "'Great Vibes',cursive" },
  { fontFamily: "'Grenze',serif" },
  { fontFamily: "'Gugi',cursive" },
  { fontFamily: "'Heebo',sans-serif" },
  { fontFamily: "'Herr Von Muellerhoff',cursive" },
  { fontFamily: "'Hind Vadodara',sans-serif" },
  { fontFamily: "'Homemade Apple',cursive" },
  { fontFamily: "'IBM Plex Serif',serif" },
  { fontFamily: "'Ibarra Real Nova',serif" },
  { fontFamily: "'Indie Flower',cursive" },
  { fontFamily: "'Inknut Antiqua',serif" },
  { fontFamily: "'Inria Serif',serif" },
  { fontFamily: "'Inter',sans-serif" },
  { fontFamily: "'Jolly Lodger',cursive" },
  { fontFamily: "'Josefin Sans',sans-serif" },
  { fontFamily: "'Jost',sans-serif" },
  { fontFamily: "'Jua',sans-serif" },
  { fontFamily: "'Julius Sans One',sans-serif" },
  { fontFamily: "'Kalam',cursive" },
  { fontFamily: "'Karma',serif" },
  { fontFamily: "'Katibeh',cursive" },
  { fontFamily: "'Kelly Slab',cursive" },
  { fontFamily: "'Knewave',cursive" },
  { fontFamily: "'KoHo',sans-serif" },
  { fontFamily: "'Laila',serif" },
  { fontFamily: "'Lato',sans-serif" },
  { fontFamily: "'Lemonada',cursive" },
  { fontFamily: "'Libre Baskerville',serif" },
  { fontFamily: "'Limelight',cursive" },
  { fontFamily: "'Lobster',cursive" },
  { fontFamily: "'Londrina Solid',cursive" },
  { fontFamily: "'Lora',serif" },
  { fontFamily: "'Love Ya Like A Sister',cursive" },
  { fontFamily: "'Luckiest Guy',cursive" },
  { fontFamily: "'Maitree',serif" },
  { fontFamily: "'Marck Script',cursive" },
  { fontFamily: "'Marmelad',sans-serif" },
  { fontFamily: "'Martel',serif" },
  { fontFamily: "'Maven Pro',sans-serif" },
  { fontFamily: "'Meddon',cursive" },
  { fontFamily: "'Megrim',cursive" },
  { fontFamily: "'Merienda One',cursive" },
  { fontFamily: "'Merriweather Sans',sans-serif" },
  { fontFamily: "'Merriweather',serif" },
  { fontFamily: "'Metamorphous',cursive" },
  { fontFamily: "'Miniver',cursive" },
  { fontFamily: "'Modak',cursive" },
  { fontFamily: "'Monda',sans-serif" },
  { fontFamily: "'Monoton',cursive" },
  { fontFamily: "'Montez',cursive" },
  { fontFamily: "'Montserrat Alternates',sans-serif" },
  { fontFamily: "'Montserrat',sans-serif" },
  { fontFamily: "'Mountains of Christmas',cursive" },
  { fontFamily: "'Mouse Memoirs',sans-serif" },
  { fontFamily: "'Mr De Haviland',cursive" },
  { fontFamily: "'Mukta',sans-serif" },
  { fontFamily: "'Muli',sans-serif" },
  { fontFamily: "'Neuton',serif" },
  { fontFamily: "'Nosifer',cursive" },
  { fontFamily: "'Notable',sans-serif" },
  { fontFamily: "'Noto Sans JP',sans-serif" },
  { fontFamily: "'Noto Serif KR',serif" },
  { fontFamily: "'Noto Serif',serif" },
  { fontFamily: "'Nova Script',cursive" },
  { fontFamily: "'Nunito Sans',sans-serif" },
  { fontFamily: "'Nunito',sans-serif" },
  { fontFamily: "'Oldenburg',cursive" },
  { fontFamily: "'Oleo Script Swash Caps',cursive" },
  { fontFamily: "'Oleo Script',cursive" },
  { fontFamily: "'Open Sans',sans-serif" },
  { fontFamily: "'Orbitron',sans-serif" },
  { fontFamily: "'Oswald',sans-serif" },
  { fontFamily: "'Overlock',cursive" },
  { fontFamily: "'Oxygen',sans-serif" },
  { fontFamily: "'PT Serif',serif" },
  { fontFamily: "'Pacifico',cursive" },
  { fontFamily: "'Passion One',cursive" },
  { fontFamily: "'Pathway Gothic One',sans-serif" },
  { fontFamily: "'Patrick Hand',cursive" },
  { fontFamily: "'Pattaya',sans-serif" },
  { fontFamily: "'Patua One',cursive" },
  { fontFamily: "'Philosopher',sans-serif" },
  { fontFamily: "'Play',sans-serif" },
  { fontFamily: "'Playball',cursive" },
  { fontFamily: "'Playfair Display',serif" },
  { fontFamily: "'Poiret One',cursive" },
  { fontFamily: "'Pompiere',cursive" },
  { fontFamily: "'Poppins',sans-serif" },
  { fontFamily: "'Press Start 2P',cursive" },
  { fontFamily: "'Pridi',serif" },
  { fontFamily: "'Prompt',sans-serif" },
  { fontFamily: "'Quattrocento Sans',sans-serif" },
  { fontFamily: "'Quicksand',sans-serif" },
  { fontFamily: "'Raleway Dots',cursive" },
  { fontFamily: "'Raleway',sans-serif" },
  { fontFamily: "'Rationale',sans-serif" },
  { fontFamily: "'Reem Kufi',sans-serif" },
  { fontFamily: "'Righteous',cursive" },
  { fontFamily: "'Roboto Condensed',sans-serif" },
  { fontFamily: "'Roboto Slab',serif" },
  { fontFamily: "'Roboto',sans-serif" },
  { fontFamily: "'Rochester',cursive" },
  { fontFamily: "'Rouge Script',cursive" },
  { fontFamily: "'Rubik',sans-serif" },
  { fontFamily: "'Ruluko',sans-serif" },
  { fontFamily: "'Rum Raisin',sans-serif" },
  { fontFamily: "'Russo One',sans-serif" },
  { fontFamily: "'Rye',cursive" },
  { fontFamily: "'Sacramento',cursive" },
  { fontFamily: "'Sansita',sans-serif" },
  { fontFamily: "'Sarabun',sans-serif" },
  { fontFamily: "'Satisfy',cursive" },
  { fontFamily: "'Sawarabi Mincho',sans-serif" },
  { fontFamily: "'Sevillana',cursive" },
  { fontFamily: "'Seymour One',sans-serif" },
  { fontFamily: "'Shadows Into Light Two',cursive" },
  { fontFamily: "'Shadows Into Light',cursive" },
  { fontFamily: "'Shrikhand',cursive" },
  { fontFamily: "'Sigmar One',cursive" },
  { fontFamily: "'Source Sans Pro',sans-serif" },
  { fontFamily: "'Special Elite',cursive" },
  { fontFamily: "'Spectral SC',serif" },
  { fontFamily: "'Spectral',serif" },
  { fontFamily: "'Squada One',cursive" },
  { fontFamily: "'Staatliches',cursive" },
  { fontFamily: "'Stalemate',cursive" },
  { fontFamily: "'Tangerine',cursive" },
  { fontFamily: "'Taviraj',serif" },
  { fontFamily: "'Teko',sans-serif" },
  { fontFamily: "'Timmana',sans-serif" },
  { fontFamily: "'Titillium Web',sans-serif" },
  { fontFamily: "'Tomorrow',sans-serif" },
  { fontFamily: "'Trirong',serif" },
  { fontFamily: "'Unica One',cursive" },
  { fontFamily: "'UnifrakturMaguntia',cursive" },
  { fontFamily: "'Unlock',cursive" },
  { fontFamily: "'Vampiro One',cursive" },
  { fontFamily: "'Varela Round',sans-serif" },
  { fontFamily: "'Vesper Libre',serif" },
  { fontFamily: "'Viga',sans-serif" },
  { fontFamily: "'Volkhov',serif" },
  { fontFamily: "'Vollkorn:ital@1',serif" },
  { fontFamily: "'Voltaire',sans-serif" },
  { fontFamily: "'Wendy One',sans-serif" },
  { fontFamily: "'Wire One',sans-serif" },
  { fontFamily: "'Work Sans',sans-serif" },
  { fontFamily: "'Yeseva One',cursive" },
];
const TextResourcesPanel = () => {
  function getSubstring(str, start, end) {
    const char1 = str.indexOf(start) + 1;
    const char2 = str.lastIndexOf(end);
    return str.substring(char1, char2);
  }
  console.log(getSubstring(fonts[0].fontFamily, "'", "'"));
  // let substring = getSubstring(originalString, ',', '!');
  // console. log(substring);
  return (
    <div className="bg-slate-800 h-full">
      <div className="text-sm px-[16px] pt-[16px] pb-[8px] font-semibold text-white">
        Add Text
      </div>

      {fonts.map((font) =>
        // prettier-ignore
        <TextResource sampleText={getSubstring(font.fontFamily, "'", "'")} fontSize={16} fontWeight={400} fontFamily={font.fontFamily} />
      )}
      {/* <TextResource sampleText="Title" fontSize={28} fontWeight={600} />
      <TextResource sampleText="Subtitle" fontSize={16} fontWeight={600} />
      <TextResource sampleText="Body" fontSize={14} fontWeight={400} />
      <TextResource sampleText="Caption" fontSize={12} fontWeight={400} />
      <TextResource sampleText="Heading 1" fontSize={24} fontWeight={800} />
      <TextResource sampleText="Heading 2" fontSize={20} fontWeight={800} />
      <TextResource sampleText="Heading 3" fontSize={18} fontWeight={800} />
      <TextResource sampleText="Heading 4" fontSize={16} fontWeight={800} />
      <TextResource sampleText="Heading 5" fontSize={14} fontWeight={800} />
      <TextResource sampleText="Heading 6" fontSize={12} fontWeight={800} /> */}
    </div>
  );
};

export default TextResourcesPanel;
